from __future__ import annotations

from pathlib import Path

from ..inspections.models import InspectionResult
from ..inspections.recommendations import maintenance_recommendation


def write_pdf(
    result: InspectionResult,
    path: str | Path,
    title: str | None = None,
) -> Path:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            Image,
            KeepTogether,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError as exc:
        raise RuntimeError("Install the reporting extra to generate PDF reports") from exc

    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    report_title = title or result.project.get("report_title") or "UAS Thermal Inspection Report"
    doc = SimpleDocTemplate(
        str(destination),
        pagesize=letter,
        leftMargin=0.55 * inch,
        rightMargin=0.55 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.55 * inch,
        title=report_title,
    )
    styles = getSampleStyleSheet()
    story = [Paragraph(report_title, styles["Title"]), Spacer(1, 10)]
    story.append(
        Paragraph(
            "Automated thermal analysis and anomaly classification generated by UAS Thermal Analysis.",
            styles["Italic"],
        )
    )
    story.append(Spacer(1, 14))

    summary = result.summary
    finding_count = len(result.findings)
    story.extend([Paragraph("1. Executive Summary", styles["Heading2"]), Spacer(1, 4)])
    summary_rows = [
        ["Canonical findings", finding_count],
        ["Critical", sum(item.severity.value == "critical" for item in result.findings)],
        ["Moderate", sum(item.severity.value == "moderate" for item in result.findings)],
        ["Minor", sum(item.severity.value == "minor" for item in result.findings)],
        ["Highest temperature", f"{result.statistics.maximum_c:.1f} °C"],
        [
            "Highest local ΔT",
            "—" if not result.findings else f"{max(item.delta_temperature_c for item in result.findings):.1f} °C",
        ],
    ]
    if summary is not None:
        summary_rows.insert(0, ["Images accepted / discovered", f"{summary.images_accepted} / {summary.images_discovered}"])
    table = Table(summary_rows, colWidths=[2.6 * inch, 3.4 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef2f6")),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5df")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.extend([table, Spacer(1, 14)])

    story.extend([Paragraph("2. Inspection Information", styles["Heading2"]), Spacer(1, 4)])
    sensor = " ".join(
        filter(None, [result.project.get("sensor_vendor"), result.project.get("sensor_model")])
    )
    info_rows = [
        ["Project", result.project.get("name", "")],
        ["Client", result.project.get("client", "")],
        ["Site", result.project.get("site", "")],
        ["Inspection date", result.project.get("inspection_date", "")],
        ["Operator", result.project.get("operator", "")],
        ["Asset type", result.project.get("asset_type", "")],
        ["Sensor", sensor],
        ["Source", result.source],
        ["Adapter", result.adapter],
        ["Profile", result.profile.get("name", result.project.get("profile_id", ""))],
    ]
    info_rows = [row for row in info_rows if row[1]]
    info = Table(info_rows, colWidths=[1.55 * inch, 4.45 * inch])
    info.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#e1e6eb")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.extend([info, Spacer(1, 14)])

    story.extend([Paragraph("3. Data Quality / Processing Summary", styles["Heading2"]), Spacer(1, 4)])
    quality_status = result.quality.get("status", "not recorded")
    story.append(Paragraph(f"Radiometric quality status: <b>{quality_status}</b>", styles["BodyText"]))
    for warning in result.quality.get("warnings", []):
        story.append(Paragraph(f"• {warning}", styles["BodyText"]))
    for reason in result.quality.get("reasons", []):
        story.append(Paragraph(f"• Rejection reason: {reason}", styles["BodyText"]))
    story.append(Spacer(1, 12))

    story.extend([Paragraph("4. Findings Summary", styles["Heading2"]), Spacer(1, 4)])
    rows = [["ID", "Classification", "Severity", "Confidence", "Max °C", "ΔT °C", "Location"]]
    for index, finding in enumerate(result.findings, 1):
        location = "—"
        if finding.latitude is not None and finding.longitude is not None:
            location = f"{finding.latitude:.5f}, {finding.longitude:.5f}"
        rows.append(
            [
                finding.finding_id or f"A-{index:03d}",
                finding.classification or finding.finding_type,
                finding.severity.value.upper(),
                finding.confidence.value.upper(),
                f"{finding.max_temperature_c:.1f}",
                f"{finding.delta_temperature_c:.1f}",
                location,
            ]
        )
    findings_table = Table(
        rows,
        repeatRows=1,
        colWidths=[0.55 * inch, 1.35 * inch, 0.75 * inch, 0.8 * inch, 0.55 * inch, 0.55 * inch, 1.25 * inch],
    )
    findings_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#243447")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cbd5df")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    story.extend([findings_table, Spacer(1, 14)])

    story.append(Paragraph("5. Detailed Findings", styles["Heading2"]))
    for index, finding in enumerate(result.findings, 1):
        finding_id = finding.finding_id or f"A-{index:03d}"
        elements = [Paragraph(f"{finding_id} — {finding.severity.value.upper()}", styles["Heading3"])]
        plate_path = Path(finding.annotated_image_path).with_name("finding_plate.png") if finding.annotated_image_path else None
        if plate_path and plate_path.is_file():
            elements.append(Image(str(plate_path), width=6.6 * inch, height=4.4 * inch, kind="proportional"))
        reference = finding.reference_temperature_c
        if reference is None:
            reference = finding.baseline_temperature_c
        evidence = "<br/>".join(f"• {item}" for item in finding.evidence[:6]) or "No additional evidence text recorded."
        recommendation = finding.recommendation or maintenance_recommendation(finding)
        details = (
            f"<b>Classification:</b> {finding.classification or finding.finding_type}<br/>"
            f"<b>Confidence:</b> {finding.confidence.value.upper()}<br/>"
            f"<b>Maximum:</b> {finding.max_temperature_c:.1f} °C &nbsp; "
            f"<b>Reference:</b> {reference:.1f} °C &nbsp; "
            f"<b>ΔT:</b> {finding.delta_temperature_c:+.1f} °C<br/>"
            f"<b>Reference method:</b> {finding.reference_method or 'not established'}<br/>"
            f"<b>Evidence:</b><br/>{evidence}<br/>"
            f"<b>Recommended action:</b> {recommendation}"
        )
        elements.extend([Paragraph(details, styles["BodyText"]), Spacer(1, 12)])
        story.append(KeepTogether(elements))

    story.extend([Paragraph("6. Methodology", styles["Heading2"]), Spacer(1, 4)])
    story.append(
        Paragraph(
            "Radiometric sources are validated before quantitative use. Candidate regions are evaluated "
            "with local thermal references, multi-scale contextual contrast, robust scene evidence, "
            "spatial coherence and configured inspection-profile thresholds. Severity describes the "
            "apparent thermal consequence under the active profile; confidence describes evidence strength.",
            styles["BodyText"],
        )
    )
    story.extend([Spacer(1, 10), Paragraph("7. Limitations", styles["Heading2"]), Spacer(1, 4)])
    story.append(
        Paragraph(
            "Automated findings are inspection intelligence, not thermographer certification. High "
            "temperature alone is not proof of a defect. Quantitative validity depends on source "
            "radiometry, calibration assumptions, environmental conditions, capture geometry and source "
            "metadata. Geographic accuracy is limited by the source georeferencing authority.",
            styles["BodyText"],
        )
    )
    story.extend([Spacer(1, 10), Paragraph("8. Machine-Readable Appendix", styles["Heading2"]), Spacer(1, 4)])
    story.append(
        Paragraph(
            "The inspection package includes structured CSV/JSON and GeoJSON/KML when geographic "
            "coordinates are available. The package manifest records file hashes for provenance.",
            styles["BodyText"],
        )
    )
    doc.build(story)
    return destination
